spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///test
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  resources:
    static-locations: classpath:/static/
server:
  port: 9999
mybatis:
  mapper-locations: classpath:/mapper/*.xml
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
